##' This function prepares functions that evaluate the strings generated by \code{getAQ}. The default quantities for mean calculation over tree are `cost` and `qol`, but others can be specified and will work as long as these variables are defined at all nodes of the tree.
##'
##' @title Make functions to evaluate tree
##' @param node 
##' @param qnt 
##' @return A \code{list} of functions
##' @author Pete Dodd
##' @export
makeTfuns <- function(node,qnt=c('cost','qol')){
    ss <- list()
    for(i in seq_along(qnt)) ss[[qnt[i]]] <- getAQ(node,qnt[i])
    for(i in seq_along(qnt)) ss[[i]] <- parse(text=ss[[i]])
    ans <- list()
    for(i in seq_along(qnt)) ans[[paste0(qnt[i],'fun')]] <- function(data) eval(ss[[i]],envir=data)
    ans
}
